### ISSUE TITLE
Can we get reviews on draft proposal, which we submit through GsoC website? 

### ISSUE THREAD

**Issue by pandyamarut** [postmanlabs/gsoc#19]
@codenirvana  It would be great if I can have a word with you over this somewhere.

**Comment by ttzztztz** [comment]
Same question. I am hoping to receive some comments on that.

**Comment by ttzztztz** [comment]
@umeshp7

**Comment by ankit-m** [comment]
We will be doing one round of review on draft proposals submitted via GSoC website. However, please ensure that the draft proposal meets all our guidelines mentioned here - https://summerofcode.withgoogle.com/organizations/4769443776823296/ and is ready for review.

Make sure that if you have specific questions, you add them as comments or highlight them. Due to time constraints and volume of proposals, it won't be possible for us to do more than one review of draft proposals.

**Comment by jimc404** [comment]
@ankit-m What's the last date till when we can submit a draft and get feedback?
